      - name: Render CV
        run: rendercv render Miquel_Obrador-Reina_CV.yaml # <-- AQUÍ ESTABA EL ERROR SEGURAMENTE
        
      - name: Prepare Pages directory
        run: |
          mkdir -p pages_output
          cp rendercv_output/*.pdf pages_output/
          cp index.html pages_output/
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Ahora subimos la carpeta que hemos preparado con ambos archivos
          path: pages_output 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4